### ISSUE TITLE
Disable "default" jobs

### ISSUE THREAD

**Issue by paula-tataru** [tabdelaal/scRNAseq_Benchmark#12]
Hi,

I am trying to run SVM and SVM_rejection using the snakemake and singularity pipeline on a new dataset. In the configuration file I have only listed the two tools.

When running snakemake, I get the list of the jobs that will be run:
```
Job counts:
        count   jobs
        1       SVM
        1       SVM_rejection
        1       all
        2       evaluate
        1       generate_dropouts_feature_rankings
        6
```

Is it possible to disable the evaluate and generate_dropouts_feature_rankings jobs? The reasons I want this are as follows.

1. I want to change the evaluation and therefore am planning to manually run an updated evaluate.R on the results.

2. The generate_dropouts_feature_rankings rule is failing on my data because it is too big (snippet from the log):
```
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (58184, 11261) and data type float64
```

Thank you.

**Comment by DavyCats** [comment]
The evaluate scripts probably won't take too long to run, so it's probably easiest to just ignore those outputs. Otherwise you can try adjusting the Snakefile:
At line 15: 
```python
    tool_outputs = expand(
        "{output_dir}/evaluation/{measure}/{tool}.csv",
        tool=config["tools_to_run"],
        output_dir=config["output_dir"],
        measure=["Confusion", "F1", "PopSize", "Summary"])
```
would have to become something like:
```python
    tool_outputs = expand(
        "{output_dir}/{tool}/{tool}_true.csv",
        tool=config["tools_to_run"],
        output_dir=config["output_dir"])
```
Then the evaluation step would be skipped.

You can disable the `generate_dropouts_feature_rankings` by providing a ranking file in the config:
```YML
feature_ranking: /path/to/ranking/file
```

This ranking file should be a csv file with a ranking of the features per fold (one column per fold):
```csv
0,1,2,3,4
4632,4632,4632,4632,4632
3269,3269,3269,3269,3269
32358,38682,32358,32358,32358
38682,32358,38682,38682,38682
23282,23282,23282,23282,23282
36336,36336,36336,36336,36336
34473,34473,34473,34473,8482
8482,8482,8482,8482,34473
```
The first row is a header and the other numbers are the indexes of the genes.

Unfortunately removing the ranking altogether would be a lot of work as it is also ingrained in the wrapper scripts for the tools.

**Comment by paula-tataru** [comment]
Thank you for your answer!

I also managed to arrive to the conclusion that providing a ranking file avoids my issue, and I guess if number_of_features is set to 0, then it doesn't even matter if that file is valid or not, since it is not used.
