### ISSUE TITLE
Re-running cross-species brain atlas tests

### ISSUE THREAD

**Issue by concatenize** [tabdelaal/scRNAseq_Benchmark#9]
If I want to re-run your cross-species benchmarks, would the following tactic work?

1. Disable the feature that generates folds for cross-validation. I will need to specify the training and test sets directly.
2. In the data download from Zenodo, parse the cross-validation RData files and split them up according to which dataset is used for training and which for testing. For example, `MouseALM_HumanMTG_folds.RData` would become `train=MouseALM__test=HumanMTG_folds.RData` and `train=HumanMTG__test=MouseALM_folds.RData`.
3. Run the pipeline separately for each resulting CV folds file.

Thank you!

P.S. I got the snakemake pipeline working with singularity and cluster configuration and everything! It's always hard to get snakemake configured on a new platform, but it's really useful for me to learn more about these tools.

**Comment by DavyCats** [comment]
1. You could indeed disable the folds generation rule and provide the folds directly to the other rules. However, snakemake will only generate files that don't exist yet. As such you could also place the desired folds RData file in the output directory and name it "CV_folds.RData". Snakemake should than see it already exists and use that file instead of generating it itself.
2. I'm not exactly certain how the folds are set up in those folds.RData files from zenodo, but I believe they should be directly usable in the pipeline. Perhaps @ahmedmahfouz or @tabdelaal can comment on how the test and training data are set up in these files.

Good to hear that things are working for you!

**Comment by concatenize** [comment]
Great -- I will use a version of your first suggestion. I really appreciate your responsiveness.
